#
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM quay.io/ascend/vllm-ascend:v0.10.0rc1-310p-openeuler

ARG PIP_INDEX_URL="https://mirrors.aliyun.com/pypi/simple"
ARG COMPILE_CUSTOM_KERNELS=1
ARG SOC_VERSION=Ascend310P3
ARG PIP_NO_CACHE_DIR=1

ENV LMCACHE_TRACK_USAGE=false

WORKDIR /workspace

COPY . /workspace/LMCache-Ascend/

RUN NO_CUDA_EXT=1 pip install lmcache==0.3.12 && \
    cd /workspace/LMCache-Ascend && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    export CPLUS_INCLUDE_PATH=/usr/include/c++/12:/usr/include/c++/12/backward:/usr/include/c++/12/aarch64-openEuler-linux/:$CPLUS_INCLUDE_PATH && \
    export SOC_VERSION=${SOC_VERSION} && \
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/Ascend/ascend-toolkit/latest/`uname -i`-linux/devlib && \
    export SOC_VERSION=Ascend910B3 && \
    pip install --no-build-isolation -v -e .

CMD ["/bin/bash"]
